<?php

/**
 * 
 * Implements hook_menu()
 */
function farmosnws_menu() {
  $items = array();

  $items['admin/config/farmosnws'] = array(
    'title' => t('FarmOS NWS Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => 'farmosnws_admin_form',
    'access arguments' => 'administer users',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * 
 * Implements hook_cron()
 */
function farmosnws_cron() {
  farmosnws_get_xml();
}

/**
 *
 * get the weather data from the NWS
 */
function farmosnws_get_xml() {
  $weatherfeedsdir = variable_get('farmosnws_weather_feeds_dir');
  
  $locations = variable_get('farmosnws_locations', '');
  $location_array = explode("\n", $locations);
  $location_count = count($location_array);

  foreach ($location_array as $loc) {
    // $weather_feed_name = $weather_feed_dir . '/' . $loc . '.' . date("Ymd.His");
    $weather_feed_name = $weather_feed_dir . '/' . $uniqid($loc, FALSE) . '.xml';
    $url = "http://w1.weather.gov/xml/current_obs/" . $loc . ".xml"

    watchdog('farmosnws', 'Getting weather data for ' . $loc, array(), WATCHDOG_INFO, NULL);

    $response = drupal_http_request($url, array());

    watchdog('farmosnws', 'Response code: ' . $response->code, array(), WATCHDOG_INFO, NULL);

    // if error occurs when performing the request
    if ( $response->error ) {
      watchdog('farmosnws', $response->error, array(), WATCHDOG_ERROR, NULL);
      drupal_set_message($response->error, 'error', FALSE);
    }
    // if no errors occur when performing the request
    else{
      // if the directory doesnt exist, then create it
      if ( is_dir($weatherfeedsdir) == FALSE ) {
         mkdir($weatherfeedsdir, 775);
         watchdog('farmosnws', 'Created weather feed directory.', array(), WATCHDOG_INFO, NULL); 
      } // end if

      // save the contents retrieved
      file_put_contents($weather_feed_name, $response->data);
      watchdog('farmosnws', 'Weather data saved to ' . $weather_feed_name, array(), WATCHDOG_INFO, NULL);
    }
  } // end foreach
} // end function

/**
 * 
 * Module configuration form
 */
function farmosnws_admin_form() {
  $form = array();

  $form['farmosnws_locations'] = array(
    '#type' => 'textarea',
    '#title' => t('Locations'),
    '#description' => t('Enter the locations that you would like weather data pulled for. Each location must be entered on a separate line.'),
    '#required' => TRUE,
    '#default_value' => variable_get('farmosnws_locations'),
  );
  $form['farmosnws_weather_feeds_dir'] = array(
    '#type' => 'textfield',
    '#title' => t('Feeds Directory'),
    '#required' => TRUE,
    '#description' => t('The directory where weather feeds should be saved to.'),
    '#default_value' => variable_get('farmosnws_weather_feeds_dir');
  );

  return system_settings_form($form);
}

