site_name: FarmOS NWS
site_url: http://bitsecondal.github.io/farmosnws
repo_url: https://github.com/bitsecondal/farmosnws.git
site_author: Kenny Robinson
remote_branch: gh-pages
remote_name: origin
use_directory_urls: true
strict: true
dev_addr: 0.0.0.0:8000
